UC/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path('users/', include('users.urls')),
    path("finance/", include('finance.urls')),
    path("login/", auth_views.LoginView.as_view(), name="login"),
]

finance/urls.py
from django.urls import path, re_path
from .views import (
    home, home_wlt,
    Create_wlt, Update_wlt,  delete_wlt,
    calendar_view, transfer_funds,
    add_income, update_income,
    add_income_type, update_income_type,
    add_spending, update_spending,
    add_spending_type, update_spending_type,
    delete_filtered_dt, delete_filtered_ct,
    update_rates
)

urlpatterns = [
    path('create_wlt/', Create_wlt.as_view(), name = 'create_wlt'),
    path('home_wlt/<int:pk>/update_wlt/', Update_wlt.as_view(), name = 'update_wlt'),
    path('home_wlt/<int:pk>/delete_wlt/', delete_wlt, name = 'delete_wlt'),

#____________________________________________________________________________________________________INCOME

    path('home_wlt/<int:w_pk>/add_income/', add_income, name = 'add_income'),
    path('home_wlt/<int:w_pk>/update_income/<int:income_pk>/', update_income, name='update_income'),

    path('home_wlt/<int:w_pk>/add_income_type/', add_income_type, name='add_income_type'),
    path('home_wlt/<int:w_pk>/update_income_type/<int:pk>/', update_income_type, name='update_income_type'),


#____________________________________________________________________________________________________SPENDING

    path('home_wlt/<int:w_pk>/add_spending/', add_spending, name = 'add_spending'),
    path('home_wlt/<int:w_pk>/update_spending/<int:spending_pk>/', update_spending, name='update_spending'),

    path('home_wlt/<int:w_pk>/add_spending_type/', add_spending_type, name='add_spending_type'),
    path('home_wlt/<int:w_pk>/update_spending_type/<int:pk>/', update_spending_type, name='update_spending_type'),

#______________________________________________________________________________________________

    path('home_wlt/<int:w_pk>/delete filtered dt/', delete_filtered_dt, name = 'delete_filtered_dt'),
    path('home_wlt/<int:w_pk>/delete filtered ct/', delete_filtered_ct, name = 'delete_filtered_ct'),
    path('home_wlt/<int:pk>/calendar/', calendar_view, name='calendar'),
    path('home_wlt/<int:w_pk>/', home_wlt, name = 'home_wlt'),
    path('transfer/', transfer_funds, name='transfer_funds'),
    path('update_rates/', update_rates, name='update_rates'),
    path('', home, name = 'home'),
    ]

finance/models.py
from django.db import models
from django.contrib.auth.models import User




class Wallet(models.Model):
    W_TYPES = (
        ('a', 'account'),
        ('b', 'bank account'),
        ('c', 'cash'),
        )
    w_name = models.CharField(max_length=20, verbose_name = 'Wallet name')
    w_ticker = models.CharField(max_length=3, verbose_name = 'Currency ticker')
    w_type = models.CharField(max_length=1, choices=W_TYPES, verbose_name = 'Type')
    w_bank = models.CharField(max_length=25, verbose_name = 'Bank name', blank=True)
    w_date = models.DateField(db_index=True, verbose_name = 'Open date')
    w_balance = models.DecimalField(max_digits=12, decimal_places=2, verbose_name = 'Open balance', default=0.00)
    f_name = models.CharField(max_length=24, blank=True, verbose_name='Full wallet name')
    w_limit = models.DecimalField(max_digits=12, decimal_places=2, verbose_name = 'Limit', default=0.00)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def save(self, *args, **kwargs):
        self.f_name = f"{self.w_name} {self.w_ticker.upper()}"
        self.w_ticker = self.w_ticker.upper()
        super().save(*args, **kwargs)
    def __str__(self):
        return self.f_name
    class Meta:
        verbose_name = 'wallet'
        verbose_name_plural = 'wallets'
        ordering = ['w_name']



class Income(models.Model):
    date = models.DateField(db_index=True, verbose_name = 'Date')
    debit = models.DecimalField(max_digits=12, decimal_places=2, verbose_name = 'Sum dt')
    source = models.CharField(max_length=20, null=True, blank=True, verbose_name = 'From')
    comment = models.TextField(max_length=60, null=True, blank=True, verbose_name = 'Comment')
    income_type = models.ForeignKey('Income_type', null=True, blank=True, on_delete=models.PROTECT, verbose_name = 'Income Type')
    wallet = models.ForeignKey(Wallet, null=True, blank=True, on_delete=models.CASCADE, verbose_name = 'Wallet')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'income'
        verbose_name_plural = 'incomes'
        ordering = ['date']
    def save(self, *args, user=None, **kwargs):
        if not self.income_type:
            # Устанавливаем значение по умолчанию, если оно не задано
            self.income_type, created = Income_type.objects.get_or_create(user=user, name='no type')
        super().save(*args, **kwargs)



class Spending(models.Model):
    date = models.DateField(db_index=True, verbose_name = 'Date')
    credit = models.DecimalField(max_digits=12, decimal_places=2, verbose_name = 'Sum ct')
    destination = models.CharField(max_length=20, null=True, blank=True, verbose_name = 'To')
    comment = models.TextField(max_length=60, null=True, blank=True, verbose_name = 'Comment')
    spending_type = models.ForeignKey('Spending_type', null=True, blank=True, on_delete=models.PROTECT, verbose_name = 'Spending Type')
    wallet = models.ForeignKey(Wallet, null=True, blank=True, on_delete=models.CASCADE, verbose_name='Wallet')
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    class Meta:
        verbose_name = 'spending'
        verbose_name_plural = 'spendings'
        ordering = ['date']
    def save(self, *args, user=None, **kwargs):
        if not self.spending_type:
            # Устанавливаем значение по умолчанию, если оно не задано
            self.spending_type, created = Spending_type.objects.get_or_create(user=user, name='no type')
        super().save(*args, **kwargs)




class Income_type(models.Model):
    name = models.CharField(max_length=30, db_index=True, verbose_name ='income type')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    def __str__(self):
        return self.name
    class Meta:
        unique_together = ('name', 'user')
        verbose_name = 'income type'
        verbose_name_plural = 'income types'
        ordering = ['name']




class Spending_type(models.Model):
    name = models.CharField(max_length=30, db_index=True,  verbose_name ='spending type')
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=False)
    def __str__(self):
        return self.name
    class Meta:
        unique_together = ('name', 'user')
        verbose_name = 'spending type'
        verbose_name_plural = 'spending types'
        ordering = ['name']




class Info(models.Model):
    init_date = models.DateField(verbose_name='Init date')
    final_date = models.DateField(verbose_name='Final date')
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    def __str__(self):
        return f"Info for {self.user} from {self.init_date} to {self.final_date}"



class Rates(models.Model):
    date = models.DateTimeField(verbose_name='date')
    name = models.CharField(max_length=5, db_index=True, verbose_name='Currency')
    buy = models.DecimalField(max_digits=5, decimal_places=2, verbose_name = 'Buy')
    sell = models.DecimalField(max_digits=5, decimal_places=2, verbose_name = 'Sell')
    source = models.URLField(max_length=150, blank=True, null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name = 'rate'
        verbose_name_plural = 'rates'
        ordering = ['date']

finance/forms.py
from .models import Wallet, Income, Income_type, Spending, Spending_type, Info
from django import forms


#========================================================================================================W A L L E T S
class Form_create_wlt(forms.ModelForm):#__________________________________________Form_create_wlt
    w_date = forms.DateField(widget=forms.TextInput(attrs={'id': 'datepicker', 'placeholder': 'Choose date'}), input_formats=['%Y-%m-%d'])
    class Meta:
        model = Wallet
        fields = ['w_name', 'w_ticker', 'w_type', 'w_bank', 'w_date', 'w_balance', 'w_limit']
    def __init__(self, *args, **kwargs):
        super(Form_create_wlt, self).__init__(*args, **kwargs)
        # Установка стиля для конкретного поля
        self.fields['w_name'].widget.attrs.update({'style': 'width: 200px;'})
        self.fields['w_ticker'].widget.attrs.update({'style': 'width: 50px;'})
        self.fields['w_bank'].widget.attrs.update({'style': 'width: 200;'})




class Form_delete_wlt(forms.ModelForm):#__________________________________________Form_delete_wlt
    class Meta:
        model = Wallet
        fields = ['w_name', 'w_ticker', 'w_type', 'w_bank', 'w_date', 'w_balance', 'w_limit']




class Form_set_date_init_bal(forms.ModelForm):
    init_date = forms.DateField(
        widget=forms.TextInput(attrs={'id': 'datepicker', 'placeholder': 'Choose date'}),
        input_formats=['%Y-%m-%d']
    )
    final_date = forms.DateField(
        widget=forms.TextInput(attrs={'id': 'datepicker', 'placeholder': 'Choose date'}),
        input_formats=['%Y-%m-%d']
    )
    class Meta:
        model = Info
        fields = ['init_date', 'final_date']


#=====================================================================================================I N C O M E


class Form_add_income(forms.ModelForm):#___________________________________________Form_add_income
    date = forms.DateField(widget=forms.TextInput(attrs={'id': 'datepicker', 'placeholder': 'Choose date'}), input_formats=['%Y-%m-%d'])
    debit = forms.DecimalField(label='Sum', widget=forms.TextInput(attrs={'placeholder': 'Enter sum'}))
    class Meta:
        model = Income
        fields = ['date', 'debit', 'source', 'comment', 'income_type']
    def __init__(self, *args, user=None, **kwargs):
        super(Form_add_income, self).__init__(*args, **kwargs)
        self.user = user
        self.fields['debit'].widget.attrs.update({'style': 'width: 150px;'})
        self.fields['source'].widget.attrs.update({'style': 'width: 200px;'})
        self.fields['comment'].widget.attrs.update({'style': 'width: 200px; height:50px; padding:5px'})
        self.fields['income_type'].widget.attrs.update({'style': 'width: 150;'})
        self.fields['income_type'].queryset = Income_type.objects.filter(user=user)
    def save(self, commit=True):
        income = super().save(commit=False)
        if self.user:
            income.user = self.user
        if commit:
            income.save()
        return income




class Form_update_income(forms.ModelForm):#___________________________________________Form_update_income
    class Meta:
        model = Income
        fields = ['date', 'debit', 'source', 'comment', 'income_type']
    def __init__(self, *args, **kwargs):
        super(Form_update_income, self).__init__(*args, **kwargs)
        # Установка стиля для конкретного поля
        self.fields['source'].widget.attrs.update({'style': 'width: 150px;'})
        self.fields['comment'].widget.attrs.update({'style': 'width: 200px; height: 50px'})



class Form_add_income_type(forms.Form):#______________________________________________Form_add_income_type
    choices = forms.ModelChoiceField(
        queryset=Income_type.objects.none(),
        required=False,
        label="Choose to edit or to delete",
        widget=forms.Select(attrs={'style': 'width: 150px;'}))
    new_value = forms.CharField(
        max_length=255,
        required=False,
        label="Add new",
        widget=forms.TextInput(attrs={'style': 'width: 150px;'}))

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['choices'].queryset = Income_type.objects.filter(user=user)




class Form_update_income_type(forms.ModelForm):#_______________________________________Form_update_income_type
    class Meta:
        model = Income_type
        fields = ['name']


#======================================================================================================S P E N D I N G
class Form_add_spending(forms.ModelForm):  # __________________________________________________Form_add_spending
    date = forms.DateField(widget=forms.TextInput(attrs={'id': 'datepicker', 'placeholder': 'Choose date'}),
                           input_formats=['%Y-%m-%d'])
    credit = forms.DecimalField(label='Sum', widget=forms.TextInput(attrs={'placeholder': 'Enter sum'}))
    class Meta:
        model = Spending
        fields = ['date', 'credit', 'destination', 'comment', 'spending_type']
    def __init__(self, *args, user=None, **kwargs):
        super(Form_add_spending, self).__init__(*args, **kwargs)
        self.user = user
        self.fields['credit'].widget.attrs.update({'style': 'width: 150px;'})
        self.fields['destination'].widget.attrs.update({'style': 'width: 200px;'})
        self.fields['comment'].widget.attrs.update({'style': 'width: 200px; height:50px; padding:5px'})
        self.fields['spending_type'].widget.attrs.update({'style': 'width: 150;'})
        self.fields['spending_type'].queryset = Spending_type.objects.filter(user=user)
    def save(self, commit=True):
        spending = super().save(commit=False)
        if self.user:
            spending.user = self.user
        if commit:
            spending.save()
        return spending

class Form_update_spending(forms.ModelForm):#___________________________________________Form_update_spending
    class Meta:
        model = Spending
        fields = ['date', 'credit', 'destination', 'comment', 'spending_type']
    def __init__(self, *args, **kwargs):
        super(Form_update_spending, self).__init__(*args, **kwargs)
        self.fields['destination'].widget.attrs.update({'style': 'width: 150px;'})
        self.fields['comment'].widget.attrs.update({'style': 'width: 200px; height: 50px'})

class Form_add_spending_type(forms.Form):#______________________________________________Form_add_spending_type
    choices = forms.ModelChoiceField(
        queryset=Spending_type.objects.none(),
        required=False,
        label="Choose spending type",
        widget=forms.Select(attrs={'style': 'width: 150px;'}))
    new_value = forms.CharField(
        max_length=255,
        required=False,
        label="Add new",
        widget=forms.TextInput(attrs={'style': 'width: 150px;'}))

    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['choices'].queryset = Spending_type.objects.filter(user=user)



class Form_update_spending_type(forms.ModelForm):#_______________________________________Form_update_spending_type
    class Meta:
        model = Spending_type
        fields = ['name']


class TransferForm(forms.Form):#______________________________________________________________Transfer Form
    date = forms.DateField(widget=forms.TextInput(attrs={'id': 'datepicker', 'placeholder': 'Choose date'}),
                           input_formats=['%Y-%m-%d'])
    from_wallet = forms.ModelChoiceField(
        empty_label="Select wallet",
        queryset=Wallet.objects.none(),
        required=True,
        label="From wallet",
        widget=forms.Select(attrs={'style': 'width: 150px;'}))
    to_wallet = forms.ModelChoiceField(
        empty_label="Select wallet",
        queryset=Wallet.objects.none(),
        required=True,
        label="To wallet",
        widget=forms.Select(attrs={'style': 'width: 150px;'}))
    amount = forms.DecimalField(label="Amount", max_digits=10, decimal_places=2)
    amount_to = forms.DecimalField(label="Amount to", max_digits=10, decimal_places=2, required=False, show_hidden_initial=False)

    comment = forms.CharField(
        max_length=255,
        required=False,
        label="Comment",
        widget=forms.TextInput(attrs={'style': 'width: 150px;'}))


    def __init__(self, *args, user=None, **kwargs):
        super().__init__(*args, **kwargs)
        if user:
            self.fields['from_wallet'].queryset = Wallet.objects.filter(user=user)
            self.fields['to_wallet'].queryset = Wallet.objects.filter(user=user)

    def clean(self):
        cleaned_data = super().clean()
        amount = cleaned_data.get("amount")
        if amount and amount <= 0:
            raise forms.ValidationError("Amount must be greater than zero.")

        return cleaned_data

finance/templates/finance/tmplt_add_income.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} {{current_wlt.w_name}} :: income adding {% endblock %}


{% block header %}
    <h1>
        {% if request.GET.choice %}
            <button class="btn nav_btn btn_green"
                    onclick="location.href='{% url 'home_wlt' current_wlt.pk %}calendar/?{% for key, value in request.GET.items %}{{ key }}={{ value }}&{% endfor %}'">
                < </button>
        {% else %}
            <button class="btn nav_btn btn_green" onclick="location.href='{% url 'home_wlt' current_wlt.pk %}'"> < </button>
        {% endif %}
        Adding new income to: {{ current_wlt.f_name }}
    </h1>
{% endblock %}


{% block left_side %}
    <div class="container_dark">
        <form method='POST' action="">
            {% csrf_token %}
            <div>
                <label>{{ form.date.label }}</label>
                <div class="form_view">
                    {{ form.date }}
                </div>
                {% if form.date.errors %}
                    <div style="color: red;">{{ form.date.errors }}</div>
                {% endif %}
                </div>

             <!-- Подключение Flatpickr -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
            <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    flatpickr("#datepicker", {
                        dateFormat: "Y-m-d",
                    });
                });
            </script>


            <div>
                <label>{{ form.debit.label }}</label>
                <div class="form_view">{{ form.debit }}</div>
                {% if form.debit.errors %}
                    <div style="color: red; font-size: 12px;">{{ form.debit.errors }}</div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.source.label }}</label>
                <div class="form_view">{{ form.source }}</div>
                {% if form.source.errors %}
                    <div style="color: red;">{{ form.source.errors }}</div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.comment.label }}</label>
                <div class="form_comm">{{ form.comment }}</div>
                {% if form.comment.errors %}
                    <div style="color: red;">{{ form.comment.errors }}</div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.income_type.label }}</label>
                <div class="form_view">
                    {{ form.income_type }}
<!--                    <button class='btn nav_btn' onclick="location.href='{% url  'add_income_type' current_wlt.pk %}?{% for key, value in request.GET.items %}{{ key }}={{ value }}&{% endfor %}'">Edit</button>-->
                </div>
                {% if form.income_type.errors %}
                    <div style="color: red;">{{ form.income_type.errors }}</div>
                {% endif %}
            </div>

            <button class='btn nav_btn' type='submit' name="save">Save</button>

        </form>
    </div>
{% endblock%}

finance/templates/finance/tmplt_transfer.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %}Wallet creating{% endblock %}

{% block menu %}{% endblock %}

{% block header %}
    <h1>
        <button class="btn nav_btn btn_green" onclick="location.href='{% url 'home' %}'"> < </button>
        Transfer funds
    </h1>
{% endblock %}


{% block left_side %}
    <div class="container_dark">
        <form method='POST' action="">
            {% csrf_token %}
            <div>
                <label>{{ form.date.label }}</label>
                <div class="form_view">
                    {{ form.date }}
                </div>
                {% if form.date.errors %}
                    <div style="color: red;">{{ form.date.errors }}</div>
                {% endif %}
                </div>

             <!-- Подключение Flatpickr -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
            <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
            <script>
                document.addEventListener('DOMContentLoaded', function() {
                    flatpickr("#datepicker", {
                        dateFormat: "Y-m-d",
                    });
                });
            </script>


            <div>
                <label>{{ form.from_wallet.label }}</label>
                <div class="form_view">
                    <select id="id_from_wallet" name="from_wallet">
                        <option value="" selected disabled>Choose wallet</option>  <!-- Пустое значение по умолчанию -->
                        {% for wallet in form.from_wallet.field.queryset %}
                            <option value="{{ wallet.id }}" data-ticker="{{ wallet.w_ticker }}"
                                {% if wallet.id == form.from_wallet.value %}selected{% endif %}>
                                {{ wallet }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                {% if form.from_wallet.errors %}
                    <div style="color: red;">{{ form.from_wallet.errors }}</div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.to_wallet.label }}</label>
                <div class="form_view">
                    <select id="id_to_wallet" name="to_wallet">
                        <option value="" selected disabled>Choose wallet</option>
                        {% for wallet in form.to_wallet.field.queryset %}
                            <option value="{{ wallet.id }}" data-ticker="{{ wallet.w_ticker }}"
                                {% if wallet.id == form.to_wallet.value %}selected{% endif %}>
                                {{ wallet }}
                            </option>
                        {% endfor %}
                    </select>
                </div>
                {% if form.to_wallet.errors %}
                    <div style="color: red;">{{ form.to_wallet.errors }}</div>
                {% endif %}
            </div>

            <div id="wallet-warning" style="color: red; display: none;">
                Please select a different wallet.
            </div>


            <div>
                <label>{{ form.comment.label }}</label>
                <div class="form_comment">{{ form.comment }}</div>
                {% if form.comment.errors %}
                    <div style="color: red;">{{ form.comment.errors }}</div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.amount.label }}</label>
                <div class="form_view">{{ form.amount }}</div>
                {% if form.amount.errors %}
                    <div style="color: red;">{{ form.amount.errors }}</div>
                {% endif %}
            </div>

            <div id="amount-field" style="display: none;">
                <label>{{ form.amount_to.label }}</label>
                <div class="form_view">{{ form.amount_to }}</div>
                {% if form.amount_to.errors %}
                    <div style="color: red;">{{ form.amount_to.errors }}</div>
                {% endif %}
            </div>

            <button class='btn nav_btn' type='submit' name="save">Transfer</button>

        </form>
    </div>

<script>
    document.addEventListener("DOMContentLoaded", function() {
    let fromWalletSelect = document.getElementById("id_from_wallet");
    let toWalletSelect = document.getElementById("id_to_wallet");
    let amountField = document.getElementById("amount-field");
    let amountToInput = document.getElementById("id_amount_to");
    let walletWarning = document.getElementById("wallet-warning");

    function checkWallets() {
        let fromWallet = fromWalletSelect.value;
        let toWallet = toWalletSelect.value;

        if (fromWallet && toWallet && fromWallet === toWallet) {
            walletWarning.style.display = "block";
        } else {
            walletWarning.style.display = "none";
        }

        checkTickerDifference();
    }

    function checkTickerDifference() {
        let fromTicker = fromWalletSelect.options[fromWalletSelect.selectedIndex]?.getAttribute("data-ticker");
        let toTicker = toWalletSelect.options[toWalletSelect.selectedIndex]?.getAttribute("data-ticker");

        if (fromTicker && toTicker && fromTicker !== toTicker) {
            amountField.style.display = "block";
            amountToInput.value = ""; // Очистить поле, чтобы пользователь вводил значение
        } else {
            amountField.style.display = "none";
            amountToInput.value = "0"; // Если скрыто, то устанавливаем 0
        }
    }

    fromWalletSelect.addEventListener("change", checkWallets);
    toWalletSelect.addEventListener("change", checkWallets);

    checkWallets(); // Проверка при загрузке страницы
});


</script>






{% endblock%}

finance/templates/finance/tmplt_update_income.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} income updating {% endblock %}

{% block menu %}
{% endblock %}

{% block header %}
    <h1>Income updating</h1>
{% endblock %}

{% block left_side %}
    <div class="container_dark">
        <form method='POST' action="">
            {% csrf_token %}

            <div>
                <label>{{ form.date.label }}</label>
                <p class="form_view">{{ form.date }}</p>
                {% if form.date.errors %}
                    <div style="color: red;">{{ form.date.errors }}</div>
                {% endif %}
            </div>

            <!-- Подключение Flatpickr -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
            <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
            <script>
                flatpickr("#id_date", {  <!-- Используем ID автоматически сгенерированное Django -->
                    dateFormat: "Y-m-d",
                });
            </script>

            <div>
                <label>{{ form.debit.label }}</label>
                <div class="form_view">{{ form.debit }}</div>
                {% if form.debit.errors %}
                    <div style="color: red; font-size: 12px;">
                        {{ form.debit.errors }}
                    </div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.source.label }}</label>
                <div class="form_view">{{ form.source }}</div>
                {% if form.source.errors %}
                    <div style="color: red;">{{ form.source.errors }}</div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.comment.label }}</label>
                <div class="form_view">{{ form.comment }}</div>
                {% if form.comment.errors %}
                    <div style="color: red;">{{ form.comment.errors }}</div>
                {% endif %}
            </div>
            <br><br>
            <div>
                <label>{{ form.income_type.label }}</label>
                <div class="form_view">{{ form.income_type }}</div>
                {% if form.income_type.errors %}
                    <div style="color: red;">{{ form.income_type.errors }}</div>
                {% endif %}
            </div>

            <div>
                <button class='btn nav_btn' type='submit' name="save">Save</button>
                <button class="btn nav_btn btn_red" type="submit" name="delete">Delete</button>
            </div>
        </form>
    </div>
{% endblock %}





{% block right_side %}
{% endblock %}

finance/templates/finance/tmplt_update_spending.html
{% extends 'layout/basic.html' %}
{% load static %}

{% block title %} spending updating {% endblock %}

{% block menu %}
{% endblock %}

{% block header %}
    <h1>Spending updating</h1>
{% endblock %}

{% block left_side %}
    <div class="container_dark">
        <form method='POST' action="">
            {% csrf_token %}

            <div>
                <label>{{ form.date.label }}</label>
                <p class="form_view">{{ form.date }}</p>
                {% if form.date.errors %}
                    <div style="color: red;">{{ form.date.errors }}</div>
                {% endif %}
            </div>

            <!-- Подключение Flatpickr -->
            <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
            <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>
            <script>
                flatpickr("#id_date", {  <!-- Используем ID автоматически сгенерированное Django -->
                    dateFormat: "Y-m-d",
                });
            </script>

            <div>
                <label>{{ form.credit.label }}</label>
                <div class="form_view">{{ form.credit }}</div>
                {% if form.credit.errors %}
                    <div style="color: red; font-size: 12px;">
                        {{ form.credit.errors }}
                    </div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.destination.label }}</label>
                <div class="form_view">{{ form.destination }}</div>
                {% if form.destination.errors %}
                    <div style="color: red;">{{ form.destination.errors }}</div>
                {% endif %}
            </div>

            <div>
                <label>{{ form.comment.label }}</label>
                <div class="form_view">{{ form.comment }}</div>
                {% if form.comment.errors %}
                    <div style="color: red;">{{ form.comment.errors }}</div>
                {% endif %}
            </div>
            <br><br>
            <div>
                <label>{{ form.spending_type.label }}</label>
                <div class="form_view">{{ form.spending_type }}</div>
                {% if form.spending_type.errors %}
                    <div style="color: red;">{{ form.spending_type.errors }}</div>
                {% endif %}
            </div>

            <div>
                <button class='btn nav_btn' type='submit' name="save">Save</button>
                <button class="btn nav_btn btn_red" type="submit" name="delete">Delete</button>
            </div>
        </form>
    </div>
{% endblock %}





{% block right_side %}
{% endblock %}